config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'
  get 'home', to: 'home#index'
  root to: "home#index"
  get 'pages/about'

  get 'terms' => 'pages#terms'
  get 'about' => 'pages#about'
  

  resources :articles do
    resources :comments
  end

  scope module: 'user' do
    resources :articles, only: [:edit, :new, :destroy]
  end

  resources :articles, only: [:index, :show]

  resource :contacts, only: [:new, :create], path_names: { :new => '' }

  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments
  belongs_to :user
  
  validates :title, presence: true, length: { maximum: 140 }
  validates :text, presence: true, length: { maximum: 4000 }

  def subject
    title
  end

  def last_comment
    comments.last
  end

  def title_length
    title.length
  end

  def text_length
    text.length
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article 

  validates :author, presence: true
  validates :body, presence: true, length: { maximum: 4000 }

  def body_length
    body.length
  end
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates_presence_of  :name
  validates_presence_of  :email
  validates_presence_of  :message
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  add_flash_types :info, :error, :warning, :success

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, :only => [:new, :create, :edit, :destroy]

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
    @comments = @article.comments

    @comment = @article.comments.build

  end

  def new
  end

  def create
    @user = User.find_by(id: current_user.id)
    @article = @user.articles.new(article_params)
   
    if @article.valid?
      @article.save
      redirect_to @user.articles.last
    else
      render action: "new"
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if  @article.user_id == current_user.id 
      if @article.update(article_params)
        flash[:success] = 'Article update successfully'
        redirect_to @article
      else
        render action: "edit"
      end
    end
  end

  def destroy
    @article = Article.find(params[:id])
    if @article.destroy
      flash[:success] = 'Article destroied successfully'
      redirect_to articles_path
    end
  end


  private

  def article_params
    params.require(:article).permit(:title, :text)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, :only => [:create]

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.build(comment_params)

    if @comment.valid?
      @comment.save
      redirect_to article_path(@article)
    end

  end

  private

  def comment_params
    params.require(:comment).permit(:author, :body)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  
  def new
  end

  def create
    @contact = Contact.new(contact_params)
    
    if @contact.valid?
      @contact.save
      redirect_to action: "new"
      flash[:success] = "The message successfully send"
    else
      render action: "new"
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :email, :message)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def terms
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/edit.html.erb
<h2><%= t('articles.edit_article') %></h2>

<%= simple_format(@message) unless @message.nil? %>

<div class="col-xs-12 col-sm-12 col-md-12, col-lg-12">
	<%= form_for :article, url: article_path(@article), method: :put, data: { turbo: false } do |f| %>

		<p>
			<%= f.label :title, class: "form-label" %><br />
			<%= f.text_field :title, class: "form-control" %>
		</p>

		<p>
			<%= f.label :text, class: "form-label" %><br />
			<%= f.text_area :text, class: "form-control" %>
		</p>

		<p>
			<%= f.submit "Edit", class: "btn btn-light" %>
		</p>
	<% end %>
</div>

app/views/articles/index.html.erb
<h2><%= t("articles.our_articles") %></h2>

<hr />
<p>
	<% @articles.each do |article| %>
		<p>
			<b><%= article.title%></b><br /><br />
			<%= article.text %>
		</p>
		<p>
			<%= link_to "Show", article_path(article) %> 
		
			<% if user_signed_in? %>
				| 
				<%= link_to "New article", new_article_path %>

				<% if current_user.id == article.user_id %>
				|
					<%= link_to "Edit", edit_article_path(article) %> |
					<%= link_to "Destroy", article_path(article), data: { "turbo-method": :delete, "turbo-confirm": "Are you sure?" } %> | 
				<% end %> 
			<% end %> 
		</p>
		<hr />
	<% end %>

	<% if @articles.size == 0 &&  user_signed_in? %>
		<%= link_to "New article", new_article_path %>
	<% end %>
</p>

app/views/articles/new.html.erb
<h1><%= t('articles.new_article') %></h1>

<div class="col-xs-12 col-sm-12 col-md-12, col-lg-12">
	<%= form_for :article, url: articles_path , data: { turbo: false } do |f| %>

	<% if @article && @article.errors.any? %>
		<p>
			<ul>
			<% @article.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
			</ul>
		</p>
	<% end %>

		<p>
			<%= f.label :title, class: "form-label"  %><br />
			<%= f.text_field :title, class: "form-control" %>
		</p>

		<p>
			<%= f.label :text, class: "form-label" %><br />
			<%= f.text_area :text, class: "form-control" %>
		</p>
		
		<p>
			<%= f.submit 'Send article', class: "btn btn-light" %>
		</p>
		 
	<% end %>

</div>  

app/views/articles/show.html.erb
<h2><%= @article.title %></h2>
<p>
	<%= @article.text %>
</p>
<br />
<br />
<h4><%= t("comments.comments") %></h4>

<% @comments.each do |comment| %>
	<p>
		<b><%= comment.author %> said: </b><br />
		<i><%= comment.body %></i>
	</p>
	<hr />
<% end %>

<% if user_signed_in? %>

	<h4><%= t("comments.add_comments") %></h4>
	<div class="col-xs-12 col-sm-12 col-md-12, col-lg-12">
		<%= form_for([@article, @comment]) do |f| %>
			
			<% if @comment && @comment.errors.any? %>
				<p>
					<ul>
					<% @comment.errors.full_messages.each do |msg| %>
						<li><%= msg %></li>
					<% end %>
					</ul>
				</p>
			<% end %>

			
			<%= f.hidden_field :author, value: current_user.username.capitalize %>

			<p>
				<%= f.label :body, class: "form-label" %><br /><br />
				<%= f.text_area :body, class: "form-control" %>
			</p>
			<p>
				<%= f.submit 'Send comment', class: "btn btn-light" %>
			</p>
			<% end %>
	</div>
	<% else %>
			<p>Please 
				<%= link_to "sign in", new_user_session_url %> or
				<%= link_to "register", new_user_registration_url %>
				to leave comments.
			</p>
	<% end %>

app/views/contacts/create.html.erb
<h2>Thanks</h2>

app/views/contacts/new.html.erb
<h1><%= t("contacts.contact_us") %></h1>
<br />
<br />

<%= form_for :contact, url: contacts_path, data: { turbo: false } do |f| %>
	
	<% if @contact && @contact.errors.any? %>
		<p>
			<ul>
			<% @contact.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
			</ul>
		</p>
	<% end %>

	<div class="col-xs-12 col-sm-12 col-md-12, col-lg-12">
		<p>
			<%= f.label :name, class: "form-label" %><br />
			<%= f.text_field :name, class: "form-control" %>
		</p>

		<p>
			<%= f.label :email, class: "form-label"  %><br />
			<%= f.text_field :email, class: "form-control" %>
		</p>

		<p>
			<%= f.label :message, class: "form-label"  %><br />
			<%= f.text_area :message, class: "form-control" %>
		</p>

		<p>
			<%= f.submit 'Send message', class: "btn btn-light" %>
		</p>
	</div>

<% end %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

  <div class="container py-3">
    <header>
      <div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom">
        <a href="/" class="d-flex align-items-center text-dark text-decoration-none">
          <span class="fs-4"><%= t("navbar.title") %></span>
        </a>

        <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
          <%= link_to t("navbar.about_us"), about_path, class: "me-3 py-2 text-dark text-decoration-none" %>
          <%= link_to t("navbar.articles"), articles_path, class: "me-3 py-2 text-dark text-decoration-none" %>
          <%= link_to t("navbar.contacts"), contacts_path, class: "me-3 py-2 text-dark text-decoration-none" %>
      </nav>
    </div>

    <% if user_signed_in? %>
        <%= t('users.greeting_user', username: current_user.username.capitalize) %> | <%= link_to 'Sign out', destroy_user_session_url, data: { 'turbo-method': :delete, 'turbo-confirm': 'Are you sure?' } %>
    <% else %>
        <%= link_to 'Sign in', new_user_session_url %> | 
        <%= link_to 'Sign up', new_user_registration_url %>

    <% end %>

    <br />
    <br />

    <% flash.each do |type, msg| %>
      <div class="alert alert-<%= type %>" role="alert">
        <%= msg %>
      </div>
    <% end %>

   
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1><%= t("static_pages.about_us") %></h1>

app/views/pages/terms.html.erb
<h1>Terms of Service</h1>

app/views/shared/_error_messages.html.erb
<% def error_message(object:) %>
       <ul>
      <% object.errors.full_messages.each do |msg| %>
       <li><%= msg %></li>
      <% end %>
     </ul>s
<% end %>